### ISSUE TITLE
Double click on queue list breaks Tauon

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/tauonmb#25]
Hello. 
To reproduce it, add one or more folders or tracks to de queue, then go to the list on the left and double click a title. Taoun will shut down. Im on Manjaro cinnamon (latest)

**Comment by Taiko2k** [comment]
I seem to be having trouble replicating this. Can you show me the error when running from terminal? 

To launch it in terminal: `python /opt/tauon-music-box/tauon.py`

**Comment by legion1978** [comment]
this is te error output

Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 21767, in <module>
    queue_box.draw(0, gui.panelY + pl_box_h, gui.lspw, full - pl_box_h)
  File "/opt/tauon-music-box/tauon.py", line 17737, in draw
    self.draw(x, y, w, h)
  File "/opt/tauon-music-box/tauon.py", line 17737, in draw
    self.draw(x, y, w, h)
  File "/opt/tauon-music-box/tauon.py", line 17737, in draw
    self.draw(x, y, w, h)
  [Previous line repeated 989 more times]
  File "/opt/tauon-music-box/tauon.py", line 17651, in draw
    ddt.draw_text((x + (10 * gui.scale), yy + 2 * gui.scale), "Up Next:", [80, 80, 80, 255], 211, bg=self.bg)
  File "/opt/tauon-music-box/t_modules/t_draw.py", line 304, in draw_text
    return self.__draw_text_cairo(location, text, colour, font, max_w, bg, align)
  File "/opt/tauon-music-box/t_modules/t_draw.py", line 186, in __draw_text_cairo
    self.__render_text(sd, x, y, range_top, range_height, align)
  File "/opt/tauon-music-box/t_modules/t_draw.py", line 163, in __render_text
    SDL_RenderCopy(self.renderer, sd[1], None, sd[0])
ctypes.ArgumentError: argument 1: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object

**Comment by Taiko2k** [comment]
Thanks, I've figured out the problem now.

The existing code assumed that if mouse button was released it must not be clicked down. But it is actually possible by clicking quick enough before a single tick has completed. 

I've fixed this now.

**Comment by legion1978** [comment]
awesome.
